name: Firebase deployment

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.FIREBASE_PASSWORD }}" | firebase login --no-localhost
        env:
          FIREBASE_PASSWORD: ${{ secrets.FIREBASE_PASSWORD }}

      - name: Build the App
        run: npm install
      - run: npm run build

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
