name: Firebase deployment

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_CI_TOKEN }} --only hosting
