name: Firebase deployment
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Build the App
        run: npm run build

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
